### ISSUE TITLE
大佬大佬，最新版本windows跑不起来

### ISSUE THREAD

**Issue by hengwuming** [TNanko/Scripts#14]

**Comment by hengwuming** [comment]
C:\Users\Administrator\Desktop\Scripts-master\scripts>python qq_read.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Scripts-master\scripts\qq_read.py", line
25, in <module>
    from bin import schedule
  File "C:\Users\Administrator\Desktop\Scripts-master\bin\schedule.py", line 15,
 in <module>
    from crontab import CronTab
ModuleNotFoundError: No module named 'crontab'

C:\Users\Administrator\Desktop\Scripts-master\scripts>

**Comment by hengwuming** [comment]
没下依赖包.......

**Comment by hengwuming** [comment]
安装了依赖包结果是这样的
D:\Scripts-master\scripts>python qq_read.py
Traceback (most recent call last):
  File "D:\Scripts-master\scripts\qq_read.py", line 712, in <module>
    main()
  File "D:\Scripts-master\scripts\qq_read.py", line 708, in main
    qq_read()
  File "D:\Scripts-master\scripts\qq_read.py", line 424, in qq_read
    config_latest, config_current = read()
  File "D:\Scripts-master\utils\configuration.py", line 70, in read
    config_current = yaml.load(obj, Loader=yaml.FullLoader)  # <class 'dict'>
  File "C:\Python39\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Python39\lib\site-packages\yaml\constructor.py", line 49, in get_sin
le_data
    node = self.get_single_node()
  File "C:\Python39\lib\site-packages\yaml\composer.py", line 36, in get_single
node
    document = self.compose_document()
  File "C:\Python39\lib\site-packages\yaml\composer.py", line 55, in compose_do
ument
    node = self.compose_node(None, None)
  File "C:\Python39\lib\site-packages\yaml\composer.py", line 84, in compose_no
e
    node = self.compose_mapping_node(anchor)
  File "C:\Python39\lib\site-packages\yaml\composer.py", line 133, in compose_m
pping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Python39\lib\site-packages\yaml\composer.py", line 84, in compose_no
e
    node = self.compose_mapping_node(anchor)
  File "C:\Python39\lib\site-packages\yaml\composer.py", line 133, in compose_m
pping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Python39\lib\site-packages\yaml\composer.py", line 84, in compose_no
e
    node = self.compose_mapping_node(anchor)
  File "C:\Python39\lib\site-packages\yaml\composer.py", line 133, in compose_m
pping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Python39\lib\site-packages\yaml\composer.py", line 84, in compose_no
e
    node = self.compose_mapping_node(anchor)
  File "C:\Python39\lib\site-packages\yaml\composer.py", line 133, in compose_m
pping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Python39\lib\site-packages\yaml\composer.py", line 82, in compose_no
e
    node = self.compose_sequence_node(anchor)
  File "C:\Python39\lib\site-packages\yaml\composer.py", line 110, in compose_s
quence_node
    while not self.check_event(SequenceEndEvent):
  File "C:\Python39\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Python39\lib\site-packages\yaml\parser.py", line 382, in parse_block
sequence_entry
    if self.check_token(BlockEntryToken):
  File "C:\Python39\lib\site-packages\yaml\scanner.py", line 116, in check_toke

    self.fetch_more_tokens()
  File "C:\Python39\lib\site-packages\yaml\scanner.py", line 223, in fetch_more
tokens
    return self.fetch_value()
  File "C:\Python39\lib\site-packages\yaml\scanner.py", line 577, in fetch_valu

    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "D:\Scripts-master/config/config.yml", line 47, column 15

**Comment by TNanko** [comment]
忘记把包给导出到 requirements.txt 了，现在好了
