### ISSUE TITLE
GitHub actions运行报错

### ISSUE THREAD

**Issue by xushen1994** [TNanko/Scripts#26]
GitHub actions运行报错怎么解决哦。
![QQ图片20210103111756](https://user-images.githubusercontent.com/50359013/103471048-02207400-4db6-11eb-8e3a-390b7513e49c.png)
获取最新配置文件版本成功！
检测到最新的配置文件版本号为v1.4.0，当前配置文件版本号：v1.3.6，可能出现新的脚本配置或者当前版本配置变更
访问 https://raw.githubusercontent.com/TNanko/Scripts/master/config/config.yml.example 查看最新配置文件
检测到最新的脚本版本号为v1.4.0，当前脚本版本号：v1.3.5
Traceback (most recent call last):
File "./scripts/qq_read.py", line 745, in
main()
File "./scripts/qq_read.py", line 741, in main
qq_read()
File "./scripts/qq_read.py", line 454, in qq_read
log_parameters = qq_read_config['log']
KeyError: 'log'
Error: Process completed with exit code 1.

**Comment by xushen1994** [comment]
今天早上9点开始报错的，之前都是正常运行

**Comment by xushen1994** [comment]
已解决，配置文件缺少日志配置
